#! /bin/sh

pgrep -x sxhkd > /dev/null || sxhkd &
~/.config/polybar/./launch.sh &
picom &

bspc monitor -d 1 2 3 4 5 6 7 8 9 10
#bspc monitor -d I II III IV V VI VII VIII IX X

bspc config border_width         0
bspc config window_gap           7

bspc config split_ratio          0.52
bspc config borderless_monocle   true
bspc config gapless_monocle      true

#wallpapers
#feh -z --bg-fill ~/wallpapers/pixel-art/**
#feh -z --bg-fill ~/wallpapers/pixel-art/wallhaven-ymp23d.png
feh -z --bg-fill /usr/share/backgrounds/wallhaven-289q2x.jpg
#feh -z --bg-fill ~/wallpapers/pixel-art/wallhaven-9d6m2w.png
#feh -z --bg-fill ~/wallpapers/pixel-art/wallhaven-1kxp9g.jpg
#feth -z --bg-fill ~/wallpapers/pixel-art/wallhaven-3z5586.jpg

#toggle layouts
#setxkbmap -layout us,latam -option grp:win_space_toggle
setxkbmap -layout us,latam -option grp:shift_caps_toggle

#mouse window focus
bspc config focus_follows_pointer true

bspc rule -a Gimp desktop='^8' state=floating follow=on
bspc rule -a Chromium desktop='^2'
bspc rule -a mplayer2 state=floating
bspc rule -a Kupfer.py focus=on
bspc rule -a Screenkey manage=off

input set-prop "Elan Touchpad" "libinput Natural Scrolling Enabled" 1
