[shell]
program = "/bin/zsh"

[window]
decorations = "none"
startup_mode = "Maximized"
opacity = 0.85
blur = true

[colors.primary]
background = "#0f101a"
foreground = "#c5c9de"

[colors.normal]
black = "#181a29"
blue = "#93bbff"
cyan = "#98e4ff"
green = "#cdea9f"
magenta = "#d3a7ee"
red = "#F07178"
white = "#bfd5de"
yellow = "#ffd47e"

[colors.bright]
black = "#282a40"
blue = "#a3c5ff"
cyan = "#98fffd"
green = "#e0ffad"
magenta = "#d6afed"
red = "#eb7f84"
white = "#d1e5ed"
yellow = "#ffee7e"

[cursor]
blink_interval = 600

[cursor.style]
shape = "Block"
blinking = "On"

[font]
size = 11.0

[font.bold]
family = "Mononoki Nerd Font"
style = "Bold"

[font.bold_italic]
family = "Mononoki Nerd Font"
style = "Bold Italic"

[font.italic]
family = "Mononoki Nerd Font"
style = "Italic"

[font.normal]
family = "Mononoki Nerd Font"
style = "Regular"

# ============================
# KEYBINDINGS
# ============================

[[keyboard.bindings]]
action = "SpawnNewInstance"
key = "Return"
mods = "Control|Shift"

[[keyboard.bindings]]
action = "Paste"
key = "Paste"

[[keyboard.bindings]]
action = "Copy"
key = "Copy"

[[keyboard.bindings]]
action = "ScrollPageUp"
key = "U"
mods = "Control|Shift"

[[keyboard.bindings]]
action = "ScrollPageDown"
key = "D"
mods = "Control|Shift"

[[keyboard.bindings]]
action = "ScrollToTop"
key = "T"
mods = "Control|Shift"

[[keyboard.bindings]]
action = "ScrollToBottom"
key = "B"
mods = "Control|Shift"

[[keyboard.bindings]]
action = "ResetFontSize"
key = "Key0"
mods = "Control"

[[keyboard.bindings]]
action = "IncreaseFontSize"
key = "Plus"
mods = "Control"

[[keyboard.bindings]]
action = "DecreaseFontSize"
key = "Minus"
mods = "Control"
